import type { Metadata } from "next";
import localFont from "next/font/local";
import {Theme, Flex, Box, Heading, Em, Text} from "@radix-ui/themes";

import Aside from "@/app/components/aside";

import "@radix-ui/themes/styles.css";
import "./globals.css";
import Tree from "@/app/components/tree";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
        >
            <Theme className="flex flex-col" style={{ backgroundColor: 'var(--gold-2)' }}>
                <header className="h-16 px-2 sm:px-8 box-border" style={{ backgroundColor: 'var(--gold-8)' }}>
                    <Flex justify="center" align="center" height="100%" >
                        <Tree size={1} color="#FAF9F2" />
                        <Heading
                            className="ml-2 sm:ml-4 mr-auto"
                            size="5"
                            style={{ color: 'var(--gold-2)' }}
                        >
                            <Em>FIRnest</Em>
                        </Heading>
                        <Text
                            size="5"
                            className="hidden sm:flex mx-auto"
                            style={{ color: 'var(--gold-2)'}}
                        >
                            <Em>Breathe. Bloom. Belong.</Em>
                        </Text>
                        <div className="ml-auto"></div>
                    </Flex>
                </header>
                <main className="flex flex-grow flex-col">
                    <Flex width="100%" height="100%" className="flex-grow py-4 box-border">
                        <Aside />
                        <Box className="w-full sm:w-3/4 flex-grow">
                            {children}
                        </Box>
                    </Flex>
                </main>
                <footer className="h-4" style={{ backgroundColor: 'var(--gold-8)' }}></footer>
            </Theme>
        </body>
        </html>
  );
}
