import type { Metadata } from "next";
import localFont from "next/font/local";
import {Theme, Flex, Box} from "@radix-ui/themes";

import Aside from "@/app/components/aside";

import "@radix-ui/themes/styles.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
        >
            <Theme className="flex flex-col" style={{ backgroundColor: 'var(--gold-2)' }}>
                <header className="h-16">
                    <Flex height="100%" style={{ backgroundColor: 'var(--gold-8)' }}>

                    </Flex>
                </header>
                <main className="flex flex-grow flex-col">
                    <Flex width="100%" height="100%" className="flex-grow py-4 box-border">
                        <Aside />
                        <Box className="w-3/4 flex-grow">
                            {children}
                        </Box>
                    </Flex>
                </main>
                <footer className="h-4" style={{ backgroundColor: 'var(--gold-8)' }}></footer>
            </Theme>
        </body>
        </html>
  );
}
