import type { Metadata } from "next";
import localFont from "next/font/local";
import {Theme, Flex} from "@radix-ui/themes";

import "@radix-ui/themes/styles.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
        >
        <Theme className="flex flex-col" style={{ backgroundColor: 'var(--gold-2)' }}>
        <header className="h-16">
            <Flex height="100%" style={{ backgroundColor: 'var(--gold-8)' }}>

            </Flex>
        </header>
          <main className="flex-grow">
            {children}
          </main>
          <footer className="h-4" style={{ backgroundColor: 'var(--gold-8)' }}></footer>
        </Theme>

        </body>
        </html>
  );
}
